name: Docker_Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]


jobs: 
  build:
    runs-on: ubuntu-22.04
     
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
         
      - name: Install dependencies
        run: |
          python -m pip install 
          pip install -r requirements.txt

      - name: Set up Docker Buildx
        uses: OumaimaNijaoui/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}



      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v3


      - name: Build the Docker image 
        run: docker build . --file Dockefile --tag OumaimaNijaoui/Oumaima_virtualisation:${GITHUB_SHA::8}

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME}}/oumaimanijaoui/oumaima_nijaoui:${GITHUB_SHA::8}

